var mongoose = require('mongoose');

var TodoSchema = new mongoose.Schema({
  name: String,
  completed: Boolean,
  note: String,
}, {
  versionKey: false, // for removing '_v' from database model
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at'
  }
});

TodoSchema.path('name').validate(function (name) {
  return name.length;
}, 'Name cannot be blank');

// Duplicate the ID field.
TodoSchema.virtual('id').get(function() {
  return this._id;
});

// Ensure virtual fields are serialised.
TodoSchema.set('toJSON', {
  virtuals: true,
  transform: function(doc, ret, options) {
    delete ret["_id"]; // generated by default id key
    return ret;
  }
});
// Todo - model name
module.exports = mongoose.model('Todo', TodoSchema);
